### ISSUE TITLE
Att det ska funka med fler lag

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#1]
Att det ska funka med fler lag

**Comment by kvarak** [comment]
Superviktigt för mig med, juniorlag också vill jag ha. Men stötte på patrull när jag testade och vet inte riktigt hur jag ska göra. Kommer jobba på denna när de "enkla" är klara.

**Comment by kvarak** [comment]
Ställt lite frågor för att kolla varför jag inte kan hämta data för andralaget. Återkommer till denna när jag vet mer.

**Comment by kvarak** [comment]
Bug rapport bekräftad av utvecklare av biblioteket jag använder, fix är nog på gång.

https://framagit.org/Pierre86/pychpp/-/issues/1

**Comment by kvarak** [comment]
Goda nyheter @VilijamRigo. Biblioteket är uppdaterat så att nu kan man kolla på sekundära lag. Jag har bekräftat att det funkar och kommer jobba på detta som nästa grej :)
