### ISSUE TITLE
Spelare - Gruppera spelare

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#11]
Skulle vara intressant om man skulle kunna 'kategorisera' sina spelare. 
Antingen med färg, ikon eller namn (eller alla tre).

ex.

![image](https://user-images.githubusercontent.com/66732847/84877700-1f475c80-b089-11ea-8765-3f08028a354a.png)

**Comment by kvarak** [comment]
Denna jobbar jag på nu, tror jag vet hur jag ska göra.

**Comment by kvarak** [comment]
Exempel på hur det kan se ut:
<img width="382" alt="Screenshot 2020-06-21 at 00 10 39" src="https://user-images.githubusercontent.com/2912566/85212495-b5aea300-b353-11ea-9ff8-20d017551a5d.png">

**Comment by VilijamRigo** [comment]
![image](https://user-images.githubusercontent.com/66732847/85224370-432cda00-b3ca-11ea-97d4-8646f742131f.png)

**Comment by VilijamRigo** [comment]
Jag kan inte välja någon grupp eller skapa egna grupper.

**Comment by kvarak** [comment]
Du skapar grupper i profile, de är "globala" för alla lag (i framtiden).

**Comment by VilijamRigo** [comment]
![image](https://user-images.githubusercontent.com/66732847/85224618-d4508080-b3cb-11ea-8b9b-a0e5fedf23f5.png)

**Comment by VilijamRigo** [comment]
Finns det någon möjlighet för att få en color picker? (personligen har jag bra koll på färger, men det behövs nog om andra ska använda appen)

**Comment by VilijamRigo** [comment]
Det blir så här när jag skapat två grupper och testar:
![image](https://user-images.githubusercontent.com/66732847/85224770-e67eee80-b3cc-11ea-831c-e0df3887e6ff.png)

![image](https://user-images.githubusercontent.com/66732847/85224738-b8011380-b3cc-11ea-9ec5-4571b3ac83f0.png)

Skulle man kunna göra så att de som är okategoriserade alltid hamnar nedanför de som är det? eller att det är det man styr med order?

**Comment by kvarak** [comment]
Jag har googlat lite, har lagt colorpicker på is, men skapar en issue för framtida förbättring.

Ja, jag var inte helt hundra på om de okategoriserade borde hamna först eller sist (hade ingen riktigt åsikt om det), men nu har vi en, jag lägger de sist. :)

Tack!

**Comment by VilijamRigo** [comment]
Det screenshotsen visar i förra kommentaren var att jag inte får färgerna att funka. 


Det ligger även ett tomt val i listan, det inte om det är ett val eller om det råkat bli så?
![image](https://user-images.githubusercontent.com/66732847/85224881-b3892a80-b3cd-11ea-9d88-1028b93fea44.png)

**Comment by VilijamRigo** [comment]
"Ja, jag var inte helt hundra på om de okategoriserade borde hamna först eller sist (hade ingen riktigt åsikt om det), men nu har vi en, jag lägger de sist. :)"

Om det är möjligt så skulle jag gärna se att om man sätter order till "-1" så kommer det ovan de okategoriserade och sätter man det till "1" så kommer det under.

**Comment by VilijamRigo** [comment]
Det skulle också vara bra om det visades vilken grupp de tillhör när man öppnar dem. 
![image](https://user-images.githubusercontent.com/66732847/85225081-e8e24800-b3ce-11ea-96fc-7cc11beed6f2.png)
