### ISSUE TITLE
Login - Keep logged in

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#14]
Jag vet inte om det kanske bara är hos mig (jag har problem med att hålla mig inloggad på ställen i Chrome).

Det kanske är så automatiskt, men skulle det gå att ha en "keep me logged in"-checkbox?

**Comment by kvarak** [comment]
Hmm, jag är inloggad hela tiden. Och det är så jag gjort. Det funkar inte på mobilen, för min chrome på mobilen rensar session cookies hela tiden, så jag har ingen kontroll på det (på websidan alltså). 

När du säger "keep logged in", menar du att du måste logga in på min sida, eller blir skickad till hattrick för godkännande?

**Comment by VilijamRigo** [comment]
Ok, då kan vi stänga denna. Jag har problem med att hålla mig inloggad på andra siter med.

**Comment by VilijamRigo** [comment]
Nice
![image](https://user-images.githubusercontent.com/66732847/85853722-51f10380-b7b3-11ea-82f6-9b98d0b251f6.png)
