### ISSUE TITLE
Spelare - Sortering

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#17]
När man sorterar på de olika kolumnerna så sorterar den stigande, vilket givetvis är bra på namn och så.
Skulle man kunna sortera olika kolumner på olika saker vid första klick?
Så det är fallande på förmågor? (så man slipper klicka två gånger)

**Comment by kvarak** [comment]
Vet inte om jag kan, men det är värt att kolla.

**Comment by kvarak** [comment]
Javascript filen är cachad och de är svåra att uppdatera. Reloada http://94.254.7.118:5000/static/sorttable.js för att uppdatera den.

**Comment by VilijamRigo** [comment]
Är osäker på vad du menar. Är detta till mig?

**Comment by kvarak** [comment]
Jo, alltså, denna är fixad, men jag såg ingen skillnad, så jag var tvungen att uppdatera js filen separat för att det skulle funka. Tänkte bara dela med mig :)
