### ISSUE TITLE
Tidslinje för spelare

### ISSUE THREAD

**Issue by kvarak** [kvarak/htstatus#19]
Det är många saker som baseras på tid. Ex ändringar sedan en viss tid, senaste gången en ändring skett eller en graf över händelser för en spelare.

Implementera funktioner som:
- ger värdena på en spelare ett visst datum.
- returnerar ändringar mellan två datum.

**Comment by VilijamRigo** [comment]
#3

**Comment by kvarak** [comment]
I've implemented some things for the "what happened last week", so I don't think I need an issue for this, I'll just implement the things when I need them.
