### ISSUE TITLE
Training - Forecast for the next increase

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#2]
Att man kan se prognos för träningsökning

**Comment by kvarak** [comment]
Prognoser är för mig lite svårt att veta, då behöver jag läsa på algoritmerna för hur det ska räknas ut. Vilket det iofs borde finnas massa att hitta "där ute".

**Comment by kvarak** [comment]
Moved to vision: https://github.com/kvarak/htstatus/wiki
