### ISSUE TITLE
App - mobilapp

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#20]
Hur mycket jobb skulle det krävas för att göra detta till en mobil app?

**Comment by kvarak** [comment]
Massa :P

Men jag använder en sak som gör om det till en ok mobilwebbsida. Testa lite, det är inte superbra pga tabellerna, men det är helt klart användbar tycker jag.

**Comment by VilijamRigo** [comment]
Kan man visa olika tabeller i mobilversionen och datorversionen?

**Comment by kvarak** [comment]
Inte som det är nu. Just nu så gör jag inget för att det ska funka med mobil, det sköter det ramverk jag använder, den formatterar om baserat på skärmstorlek. Jag är väldigt tveksam till att jag kommer göra något speciellt för mindre skärm. Det kommer inte vara värt den effort, för detta är en stor förändring.

**Comment by kvarak** [comment]
WIll stick with the web app, mobile app is another beast.
