### ISSUE TITLE
Se ändringarna som hänt när man gör update

### ISSUE THREAD

**Issue by kvarak** [kvarak/htstatus#21]
När man uppdaterar, så vill man se om något hänt.

Visa:
- Ändringar sen sist man uppdaterade och
- Ändringar sedan en vecka

**Comment by VilijamRigo** [comment]
![image](https://user-images.githubusercontent.com/66732847/85957674-8c16fc80-b98f-11ea-9f76-f4ffa9a2f570.png)

**Comment by kvarak** [comment]
Yes, should make that nicer :)
