### ISSUE TITLE
Spelare - Gruppera - Ordning

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#25]
"Ja, jag var inte helt hundra på om de okategoriserade borde hamna först eller sist (hade ingen riktigt åsikt om det), men nu har vi en, jag lägger de sist. :)"

Om det är möjligt så skulle jag gärna se att om man sätter order till "-1" så kommer det ovan de okategoriserade och sätter man det till "1" så kommer det under.

_Originally posted by @VilijamRigo in https://github.com/kvarak/htstatus/issues/11#issuecomment-647123695_

**Comment by VilijamRigo** [comment]
Eller tvärtom

**Comment by kvarak** [comment]
Eller så kanske man kan markera en grupp i listan (i profile där man ändrar på grupperna) som är default gruppen. Så kan man sätta order och färger på dem själv?

**Comment by VilijamRigo** [comment]
Skulle du kunna skapa en default grupp som alla spelare tillhör innan man
väljer något aktivt?
Att aktivt behöva sätta spelarna i en tom grupp själv motverkar lite detta
ärende.

Den mån 22 juni 2020 14:14Albert Rigo <notifications@github.com> skrev:

**Comment by kvarak** [comment]
Jo, precis så menar jag :)

Edit: nej, inte precis så, men typ så :P

**Comment by VilijamRigo** [comment]
Kan du sätta Default Order till 0?

Eftersom användaren kan sätta egen order, kan man själv välja om man vill ha minus eller plus.

**Comment by kvarak** [comment]
Nja. Två anledningar. Jag vill att default beteende är att den är sist. Och erfarenhet säger att förvånansvärt många har svårt med negativa tal. Detta är för alla.

**Comment by VilijamRigo** [comment]
Ok

Den tis 23 juni 2020 07:03Albert Rigo <notifications@github.com> skrev:
