### ISSUE TITLE
Previous increases

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#3]
Att man tydligt kan se när spelare fått/tappat I färdighet

**Comment by kvarak** [comment]
Förtydligande:

I spelartabellen, lägg till en kolumn som visar hur många veckor sen det var en ökning. I framtiden, också visa när den borde öka sig när #2 är klar.

**Comment by VilijamRigo** [comment]
Finns det någon möjlighet att ta data från HTs sida över tidigare träning?
![image](https://user-images.githubusercontent.com/66732847/85264259-b426cd00-b470-11ea-9fda-4300ab925c1a.png)

**Comment by kvarak** [comment]
Hmm, det finns en `trainingevents` som ger de senaste 4 eller 5 ändringarna för en spelare, vilket jag antar är det de använder som bas för denna sida. Det skulle nog funka.

**Comment by VilijamRigo** [comment]
Is there a way to decide from what week the changes are from? Instead of first update.
Like a drop-down that I could choose "W2-S76" and the plusses or minuses would be from that week to current day?

**Comment by kvarak** [comment]
Is that for a player (single player view), or in the table where you can see all players?

Digging deeper; What is the thing you would like to see/do that you can't now? If you can, formulate something like "I would like X because then I can [see/do] Y". I need to understand your "why" so that I can weigh solutions with current implementation. :)

My thought with issue is to show the increases, in detail, on the single player view. How many weeks between all increases and try to guess when the next increase is.

**Comment by VilijamRigo** [comment]
I'd like this in the team view, for an easier overview. 
Preferably a drop-down that I could choose week (for example: "W2-S76") and the plusses or minuses would be from that week to current day?

Basically be able to change the column "since".

This would make it easier to see how many changes has occurred since that week.  
![image](https://user-images.githubusercontent.com/66732847/97637497-10ab8180-1a3b-11eb-96b0-5b05de510469.png)

**Comment by kvarak** [comment]
Ok, noted. I haven't planned to change the team view much, but I'll see what I can do. :)

**Comment by kvarak** [comment]
@VilijamRigo I've added a statistics page, where you can see the logged increases. Do you think this is in the right direction for you as well? I don't want to make the team view to complicated, and want to move the training and such things to a different page. Next step on the stats page is to try to calculate who will increase next based on historical increases.

**Comment by kvarak** [comment]
Done
