### ISSUE TITLE
All items do not update, or are updated wrong.

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#38]
**Describe the bug**
All items do not update, or are updated wrong.
Notes update on some players, but not all.
Player number is wrong.
![image](https://user-images.githubusercontent.com/66732847/92994011-edfaf300-f4f6-11ea-9d7c-0f891c1c96ef.png)
![image](https://user-images.githubusercontent.com/66732847/92994021-fce1a580-f4f6-11ea-9ac1-3f173c107d58.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/66732847/92993997-c99f1680-f4f6-11ea-91b6-d1ff792ec51b.png)
![image](https://user-images.githubusercontent.com/66732847/92994038-1edb2800-f4f7-11ea-9fa3-abca09fa3e0a.png)

**Browser:**
 - Which one [e.g. chrome, safari]
 - Smartphone or computer

**Additional context**

**Comment by VilijamRigo** [comment]
More instances of number not changing.
Actual numbers:
![image](https://user-images.githubusercontent.com/66732847/94476361-a8b21300-01d0-11eb-905e-09b73a15407f.png)
In app:
![image](https://user-images.githubusercontent.com/66732847/94476395-b7002f00-01d0-11eb-98bc-8059fe7f8859.png)

**Comment by kvarak** [comment]
I think I have found the root cause. The update is correct, it does update the players. It's the displaying of playerdata that is wrong, it doesn't display the newest playerdata, but older (oldest?). Looking into this now.
