### ISSUE TITLE
Team you meet

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#4]
Skulle vara intressant om man skulle kunna få till att man kan se taktiker och sådant på lag man ska möta.
Det är hyfsat enkelt att klicka på lagen och kika på deras senaste matcher, men om det fanns något enklare.

**Comment by kvarak** [comment]
Ja, detta vore najs.

**Comment by kvarak** [comment]
Moved to vision: https://github.com/kvarak/htstatus/wiki
