### ISSUE TITLE
Request access as beta tester

### ISSUE THREAD

**Issue by CassioFabius** [kvarak/htstatus#42]
**What is your hattrick user or hattrick user id**
cassiolaw / 717674

**Additional information**
None.

**Comment by kvarak** [comment]
Hi CassioFabius, you should be able to go to ht.kvarak.net and try it out.

**Comment by CassioFabius** [comment]
Thanks, @kvarak! I got in.
There was an error the first time I tried to login (something with "it was not possible to import oauth token"). But I opened a new tab and tried it again and I logged in smoothly.
