### ISSUE TITLE
Support Specialty icon missing

### ISSUE THREAD

**Issue by CassioFabius** [kvarak/htstatus#43]
**Describe the bug**
Failed to load resource: the server responded with a status of 404 (NOT FOUND): ico-sp-8.png:1

**To Reproduce**
1. Go to "http://94.254.7.118:5000/player?id=TEAMID" or go to "Players" page.
2. If you have any player with support specialty, the icon in the table will be missing.

![image](https://user-images.githubusercontent.com/21185025/103995294-0e6e4d80-5177-11eb-8d5c-7806fa853538.png)

**Browser:**
 - Microsoft Edge Version 87.0.664.66 (Official build) (64-bit)
 - Computer Windows 10

**Comment by kvarak** [comment]
Thanks for noticing! I've made an update, could you please check if it works now in 0.2.44? (I don't have a player with support).

**Comment by kvarak** [comment]
Done
