### ISSUE TITLE
Skill Bar Limit/Presentation

### ISSUE THREAD

**Issue by CassioFabius** [kvarak/htstatus#44]
**Your question/topic.**
I see that player skill bars have "20" as limit:

![image](https://user-images.githubusercontent.com/21185025/104001141-01089180-517e-11eb-81f1-6ee2374c1c7e.png)

But, for example, Pedro 'Apache' Zurita (6993859) has experience level at 71 (20 + 51).

![image](https://user-images.githubusercontent.com/21185025/104002149-6a3cd480-517f-11eb-9619-bfd14b2e2744.png)

Many other players have skills over 20 (mainly experience and Set Pieces). I don't know how these skill bars will handle these values yet, but it looks like that "skill bars" make sense for skills with defined limit, as "leadership","stamina" and "form".

Would it be better to use another way to present these skill values? What do you think?

**Comment by kvarak** [comment]
I had an idea that all overflow could be written inside the blue bar, for instance is a player have 22 in set pieces, then the blue bar will be full and it will state "+2" on the blue bar. It's not yet implemented though.

But maybe a graphical view isn't needed at all? Just the numbers? (And text later on, but that will wait until I have implemented support for multiple languages).

**Comment by VilijamRigo** [comment]
For me the graphical view is important. It makes the tool more than just some datapoints.

**Comment by kvarak** [comment]
Experimenting some :)
What about this?
![Screenshot 2021-01-20 at 16 55 50](https://user-images.githubusercontent.com/2912566/105200724-6fffc600-5b40-11eb-8af5-2c8fe44704f3.png)

**Comment by VilijamRigo** [comment]
I'm not a fan of this one.

**Comment by kvarak** [comment]
Will not do this. Not in line with the graphical vision.
