### ISSUE TITLE
Startvy

### ISSUE THREAD

**Issue by VilijamRigo** [kvarak/htstatus#9]
Startvyn (dierkt efter att man loggat in) kanske ska innehålla sammanfattningar av de andra vyerna. 
Vi vet ju inte än vad som finns på de andra vyerna.

Det skulle vara intressant om ex. man snabbt fick se att det bara är två veckor kvar till förmågeökning.
Eller vad fansen säger om nästa match.

**Comment by kvarak** [comment]
Jag hade en tanke att "team"-sidan skulle innehålla detta, en för varje lag. Men det kanske är bättre att ha en samlad vy för kommande saker iofs. Sätter #5 som duplicate till denna.

**Comment by kvarak** [comment]
Gjorde en mock-up för hur denna skulle kunna se ut. Något sånt du tänkte dig? Det är startsidan. Man kommer även dit nu när man loggar in.

**Comment by VilijamRigo** [comment]
Jo, det var något sånt jag tänkt mig. Jag gillar även det som fanns nyss om senaste ändringarna (på Laget).

En sak jag funderade på var om den Vyn kunde ha något som visar översikter/jämförelse från alla lag? Men det finns stor risk att denna vy blir rörig.

**Comment by kvarak** [comment]
Senaste ändringarna (som finns på update sidan) kan man lägga upp, för det har jag klart. Sen så kan man lägga in mer o mer när man har något som man ser att "det där borde vi visa". 

Lägger in bilden här för framtiden. Tänkte ta bort mock-up'en.

![image](https://user-images.githubusercontent.com/2912566/85663202-18d46880-b6b9-11ea-975e-45d8b7408045.png)

**Comment by kvarak** [comment]
Jag kommer göra en update, sen kommer jag stänga denna så att den inte hänger kvar. Men varje gång jag gör en ändring som är värd att lägga till på framsidan, så finns det nu ett sätt att göra det på.

**Comment by VilijamRigo** [comment]
Nice
![image](https://user-images.githubusercontent.com/66732847/85853722-51f10380-b7b3-11ea-82f6-9b98d0b251f6.png)

**Comment by VilijamRigo** [comment]
I got the inspiration for this issue on the official mobile app.
That was what I had in mind then. 
I'm not a hundred percent sure I think that is what we need, but that's the kind of info I was going for.
